name: zCloud Deploy
author: zCloud <support@zcloud.ws>
description: GitHub action to deploy content on zCloud platform.
branding:
  icon: upload-cloud
  color: green
inputs:
  user-token:
    description: 'Token to authenticate the user'
    required: false
  env-token:
    description: 'Token to authenticate the app environment'
    required: false
  env:
    description: 'Environment name to create or update'
    required: true
  dir:
    description: 'Directory usage as source code to send to deploy (Optional, default value is current dir)'
    required: false
    default: ""
  cli-extra-args:
    description: 'CLI extra arguments.'
    required: false
runs:
  using: 'docker'
  image: docker://zcloudws/zcloud-cli:v1.0.5
  env:
    ZCLOUD_USER_TOKEN: ${{ inputs.user-token }}
    ZCLOUD_ENV_TOKEN: ${{ inputs.env-token }}
    ZCLOUD_ENV_NAME: ${{ inputs.env }}
    ZCLOUD_SRC_DIR: ${{ inputs.dir }}
  entrypoint: sh
  args:
    - -c
    - 'zcloud deploy ${{ inputs.cli-extra-args }}'
